version: "3.8"
networks:
  wallet_bridge:
    driver: bridge
services:
  database:
    container_name: "app_db"
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: psw
      POSTGRES_MULTIPLE_DATABASES: wallet_db,wallet_db_test
      POSTGRES_DB_PROD: wallet_db
      POSTGRES_DB_TEST: wallet_db_test
    volumes:
        - ./pkg/pg_init_scripts:/docker-entrypoint-initdb.d
        - data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - wallet_bridge
  server:
    container_name: "server"
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile
      args:
        GOBIN: /app
    environment:
      GOBIN: /app
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: psw
      POSTGRES_MULTIPLE_DATABASES: wallet_db,wallet_db_test
      POSTGRES_DB_PROD: wallet_db
      POSTGRES_DB_TEST: wallet_db_test

      HTTP_LISTEN_ADDRESS: 0.0.0.0:8080
    volumes:
      - .:/go/src/github.com/skwol/wallet
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - wallet_bridge
volumes:
  data:
  test_data: