version: "3.8"
services:
  database:
    container_name: "app_db"
    image: "postgres"
    restart: always
    volumes:
        - ./pkg/pg_init_scripts:/docker-entrypoint-initdb.d
        - data:/var/lib/postgresql/data
    env_file:
        - .env
    ports:
        - "5432:5432"
  server:
    container_name: "server"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
  test_data: