version: "3.8"
networks:
  wallet_bridge:
    driver: bridge
services:
  database_test:
    container_name: "app_db_test"
    image: "postgres:14"
    restart: always
    volumes:
        - ./pkg/pg_init_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: psw
      POSTGRES_MULTIPLE_DATABASES: wallet_db,wallet_db_test
      POSTGRES_DB_PROD: wallet_db
      POSTGRES_DB_TEST: wallet_db_test

      HTTP_LISTEN_ADDRESS: 0.0.0.0:8080
    ports:
        - "5432:5432"
    networks:
      - wallet_bridge
  server_test:
    container_name: "server_test"
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      - database_test
    networks:
      - wallet_bridge
volumes:
  data:
  test_data: