version: "3.8"
networks:
  wallet_bridge:
    driver: bridge
services:
  database_test:
    container_name: "app_db_test"
    image: "postgres:14"
    restart: always
    volumes:
        - ./pkg/pg_init_scripts:/docker-entrypoint-initdb.d
    env_file:
        - .env
    ports:
        - "5432:5432"
    networks:
      - wallet_bridge
  server_test:
    container_name: "server_test"
    build:
      context: .
      dockerfile: ./Dockerfile.test
    env_file: .env
    depends_on:
      - database_test
    networks:
      - wallet_bridge
volumes:
  data:
  test_data: